# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-HpI4m8ubbM6Oga7GguETSG2zB0KNisI
"""

a = 7.5
b = a
c = a**2 - (b/2)**2
d = c**(1/2)
s = 1/2*a*d
print("Площадь :", s)

a = int(input())
b = int(input())
c = int(input())
x = (a**2 + b**2 - c**3)/2
print(x)

a = 5
b = int(input())
c = a * b
print("Произведение", c)



a = int(input())
b = int(input())
c = (a + b)**2
print(c)

a = 15
b = 10
c = int(input())
d = (a + b)/c
print(c)

a = int(input())
b = int(input())
c = (a + b)**2
print(c)

a = int(input())
b = int(input())
c = a**2 - ((b/2)**2)
d = c**(1/2)
s = 1/2*a*d
print("Площадь :", s)

a = int(input())
b = int(input())
d = ((a**3 + 14)/5) * b
print(d)

a = int(input())
n = int(input())
b = (a**2)//n
print(b)

a = float(input())
b = float(input())
c = a/b
a1 = int(input())
b1 = int(input())
c1 = a1*b1
a2 = int(input())
b2 = int(input())
c2 = (a2%b2)
print(c, c1, c2)

n = int(input())
n1 = n//60
n2 = n1//60
n3 = n2//24
print(n1, n2, n3)

n = int(input())
n1 = n + n*n + n*n*n
print(n1)